-- 【保理】 ---------
CREATE TABLE `merchant_info` (
  `mcht_cd` varchar(30) NOT NULL DEFAULT '',
  `bran_cd` varchar(30) DEFAULT NULL,
  `mcht_name` varchar(100) DEFAULT NULL,
  `mcht_business_name` varchar(255) DEFAULT NULL,
  `mcht_org_cd` varchar(30) DEFAULT NULL,
  `mcht_business_license` varchar(30) DEFAULT NULL,
  `mcht_type` varchar(30) DEFAULT NULL,
  `mcht_service_type` varchar(30) DEFAULT NULL,
  `servcie_org` varchar(30) DEFAULT NULL,
  `reg_prov_cd` varchar(30) DEFAULT NULL,
  `reg_city_cd` varchar(30) DEFAULT NULL,
  `reg_country_cd` varchar(30) DEFAULT NULL,
  `mcht_address` varchar(255) DEFAULT NULL,
  `contact_name` varchar(255) DEFAULT NULL,
  `contact_phone` varchar(255) DEFAULT NULL,
  `contact_fax` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `bloc_mcht_cd` varchar(255) DEFAULT NULL,
  `bloc_mcht_name` varchar(255) DEFAULT NULL,
  `mcht_settlement_way` varchar(255) DEFAULT NULL,
  `approve_date` varchar(255) DEFAULT NULL,
  `lose_date` varchar(255) DEFAULT NULL,
  `service_level` varchar(255) DEFAULT NULL,
  `source_from` varchar(255) DEFAULT NULL,
  `referrer` varchar(255) DEFAULT NULL, -- ----------------------------------------------------  
  `customer_cd` varchar(255) DEFAULT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `mcc_cd` varchar(255) DEFAULT NULL,
  `org_cd` varchar(255) DEFAULT NULL,
  `legal_person_name` varchar(255) DEFAULT NULL,
  `legal_person_id_type` varchar(255) DEFAULT NULL,
  `legal_person_id_no` varchar(255) DEFAULT NULL,
  `mcht_settlement_cycle` varchar(255) DEFAULT NULL,
  `normal_clt_count` varchar(255) DEFAULT NULL,
  `undo_clt_count` varchar(255) DEFAULT NULL,
  `mcht_nature` varchar(255) DEFAULT NULL,
  `mcht_status` varchar(255) DEFAULT NULL,
  `is_risk_lp` varchar(255) DEFAULT NULL,
  `mcht_dept` varchar(255) DEFAULT NULL,
  `has_overdue` varchar(255) DEFAULT NULL,
  `financial_name` varchar(255) DEFAULT NULL,
  `financial_phone` varchar(255) DEFAULT NULL, -- ----------------------------------------------------
  `tax_reg_no` varchar(255) DEFAULT NULL,
  `settlement_model` varchar(255) DEFAULT NULL, -- ----------------------------------------------------
  `settlement_cycle` varchar(255) DEFAULT NULL,
  `settlement_way` varchar(255) DEFAULT NULL,
  `data_channel` varchar(255) DEFAULT NULL,
  `is_group_mcht` varchar(255) DEFAULT NULL,
  `is_point_card_settlement` varchar(255) DEFAULT NULL,
  `customer_no` varchar(255) DEFAULT NULL,
  `area_standard` varchar(255) DEFAULT NULL,
  `reg_capital` varchar(255) DEFAULT NULL,
  `main_business` varchar(255) DEFAULT NULL,
  `scope_of_business` varchar(255) DEFAULT NULL,
  `business_license_limit` varchar(255) DEFAULT NULL,
  `service_nature` varchar(255) DEFAULT NULL,
  `product_info` varchar(255) DEFAULT NULL,
  `mcht_mcc` varchar(255) DEFAULT NULL,
  `three_in_one_flag` char(1) DEFAULT NULL, -- ----------------------------------------------------
  `us_credit_code_no` varchar(120) DEFAULT NULL,
  `us_credit_code_start_date` varchar(32) DEFAULT NULL,
  `us_credit_code_end_date` varchar(32) DEFAULT NULL,
  `timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `gb_mcht_type` char(2) DEFAULT NULL,
  PRIMARY KEY (`mcht_cd`),
  KEY `idx_reg_prov_cd` (`reg_prov_cd`) USING BTREE,
  KEY `idx_legal_person_id_no` (`legal_person_id_no`) USING BTREE,
  KEY `idx_approve_date` (`approve_date`) USING BTREE,
  KEY `idx_reg_prov_cd_reg_city_cd` (`reg_prov_cd`,`reg_city_cd`) USING BTREE,
  KEY `idx_CO_RE_RE_RE` (`contact_phone`,`reg_prov_cd`,`reg_city_cd`,`reg_country_cd`) USING BTREE,
  KEY `idx_RE_RE_RE` (`reg_prov_cd`,`reg_city_cd`,`reg_country_cd`) USING BTREE,
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_mcht_business_license` (`mcht_business_license`(4)),
  KEY `idx_mcht_address` (`mcht_address`(4)),
  KEY `idx_legal_person_name` (`legal_person_name`(4)),
  KEY `idx_mcht_name` (`mcht_name`(4))
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

