CREATE TABLE `rc_tm_merchant_info` (
  `merchant_code` varchar(30) NOT NULL DEFAULT '' COMMENT '通金商户编号',
  `branch_code` varchar(30) DEFAULT NULL COMMENT '分支编码',
  `merchant_name` varchar(100) DEFAULT NULL COMMENT '注册名称',
  `merchant_business_name` varchar(255) DEFAULT NULL COMMENT '商户名称',
  `merchant_org_code` varchar(30) DEFAULT NULL COMMENT '商户机构码',
  `uscc` varchar(30) DEFAULT NULL COMMENT '统一社会信用码,Uniform Social Credit Code',
  `mcc` varchar(30) DEFAULT NULL COMMENT '商户行业分类码,Merchant Category Code',
  `merchant_service_type` varchar(30) DEFAULT NULL COMMENT '商户类型',
  `service_org` varchar(30) DEFAULT NULL COMMENT '专业化服务机构',
  `reg_prov_code` varchar(30) DEFAULT NULL COMMENT '注册省编号',
  `reg_city_code` varchar(30) DEFAULT NULL COMMENT '注册市编号',
  `reg_dist_code` varchar(30) DEFAULT NULL COMMENT '注册区编号',
  `merchant_address` varchar(255) DEFAULT NULL COMMENT '注册地址',
  `contact_name` varchar(255) DEFAULT NULL COMMENT '联系人姓名',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT '联系人电话',
  `contact_fax` varchar(20) DEFAULT NULL COMMENT '联系人传真',
  `contact_email` varchar(50) DEFAULT NULL COMMENT '联系人邮件',
  `bloc_merchant_code` varchar(50) DEFAULT NULL COMMENT '集团商户编码',
  `bloc_merchant_name` varchar(50) DEFAULT NULL COMMENT '集团商户名称',
  `merchant_settlement_way` varchar(10) DEFAULT NULL COMMENT '商业结算途径',
  `approve_date` varchar(20) DEFAULT NULL COMMENT '入网日期',
  `lose_date` varchar(20) DEFAULT NULL COMMENT '出网日期',
  `service_level` varchar(10) DEFAULT NULL COMMENT '服务等级',
  `merchant_source_channel` varchar(10) DEFAULT NULL COMMENT '商户来源渠道',
  `recommender` varchar(32) DEFAULT NULL COMMENT '推荐人',
  `customer_code` varchar(32) DEFAULT NULL COMMENT '统一客户代码',
  `customer_name` varchar(32) DEFAULT NULL COMMENT '统一客户姓名',
  `mcc_code` varchar(30) DEFAULT NULL COMMENT '国民经济行业分类代码',
  `org_code` varchar(255) DEFAULT NULL COMMENT '机构码',
  `legal_person_name` varchar(32) DEFAULT NULL COMMENT '法人名称',
  `legal_person_id_type` varchar(10) DEFAULT NULL COMMENT '法人证件类型',
  `legal_person_id_no` varchar(30) DEFAULT NULL COMMENT '证件号',
  `merchant_settlement_cycle` varchar(255) DEFAULT NULL COMMENT '商户结算周期',
  `normal_clt_count` varchar(255) DEFAULT NULL COMMENT '正常终端（POS）数',
  `undo_clt_count` varchar(255) DEFAULT NULL COMMENT '撤销终端数',
  `merchant_nature` varchar(255) DEFAULT NULL COMMENT '商户性质',
  `merchant_status` varchar(255) DEFAULT NULL COMMENT '商户状态',
  `is_risk_lp` varchar(255) DEFAULT NULL COMMENT '是否为风险商户法人代表',
  `merchant_dept` varchar(255) DEFAULT NULL COMMENT '商户负债额',
  `has_overdue` varchar(255) DEFAULT NULL COMMENT '是否有逾期债务',
  `financial_name` varchar(255) DEFAULT NULL COMMENT '财务联系人',
  `financial_phone` varchar(255) DEFAULT NULL COMMENT '财务联系人电话',
  `tax_reg_no` varchar(255) DEFAULT NULL COMMENT '税务登记号',
  `settlement_model` varchar(255) DEFAULT NULL COMMENT '结算方式',
  `settlement_cycle` varchar(255) DEFAULT NULL COMMENT '结算周期',
  `settlement_way` varchar(255) DEFAULT NULL COMMENT '结算途径',
  `data_channel` varchar(255) DEFAULT NULL COMMENT '数据渠道',
  `is_group_merchant` varchar(255) DEFAULT NULL COMMENT '是否为集团商户',
  `is_point_card_settlement` varchar(255) DEFAULT NULL COMMENT '是否为分开结算',
  `customer_no` varchar(255) DEFAULT NULL COMMENT '统一客户号',
  `area_standard` varchar(255) DEFAULT NULL COMMENT '地区标准',
  `reg_capital` varchar(255) DEFAULT NULL COMMENT '注册资本',
  `main_business` varchar(255) DEFAULT NULL COMMENT '主营业务',
  `scope_of_business` varchar(255) DEFAULT NULL COMMENT '经营范围',
  `business_license_limit` varchar(255) DEFAULT NULL COMMENT '营业执照有效',
  `service_nature` varchar(255) DEFAULT NULL COMMENT '服务性质',
  `product_info` varchar(255) DEFAULT NULL COMMENT '条线产品信息',
  `merchant_mcc` varchar(20) DEFAULT NULL COMMENT '商户MCC(18)',
  `three_in_one_flag` char(1) DEFAULT NULL COMMENT '是否三证合一',
  `uscc2` varchar(120) DEFAULT NULL COMMENT '统一社会信用码',
  `uscc_start_date` varchar(32) DEFAULT NULL COMMENT '统一社会信用码生效日',
  `uscc_end_date` varchar(32) DEFAULT NULL COMMENT '统一社会信用码失效日',
  `timestamp` timestamp NULL DEFAULT NULL COMMENT '时间戳',
  `is_deleted` tinyint(4) DEFAULT NULL COMMENT '逻辑删除，1.是，0.否',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_user` varchar(32) DEFAULT NULL COMMENT '创建人',
  `modify_time` datetime DEFAULT NULL COMMENT '修改时间',
  `modify_user` varchar(32) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`merchant_code`),
  KEY `idx_mc_mcc` (`merchant_code`,`mcc`),
  KEY `idx_re_re_re` (`reg_prov_code`,`reg_city_code`,`reg_dist_code`),
  KEY `idx_co_re_re_re` (`contact_phone`,`reg_prov_code`,`reg_city_code`,`reg_dist_code`),
  KEY `idx_legal_person_id_no` (`legal_person_id_no`) USING BTREE,
  KEY `idx_approve_date` (`approve_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通金商户表';
